name: CI
on: push

permissions:
  contents: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装依赖&项目打包
        run: |
          pwd
          ls

      # - name: 部署
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages
      #     folder: build